hdu_birthdays/urls.py
from django.contrib import admin
from django.urls import path

from notification.views import AdminNotificationView, NotificationView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from notification.views import handler404 as view404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('<date>/', NotificationView.as_view(), name='birthdays'),
    path('notify/<date>/', AdminNotificationView.as_view()),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = view404

birthday/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.

SEX_CHOICES = (
    ('male', 'Мужской'),
    ('female', 'Женский')
)


class Structural(models.Model):
    name = models.CharField('Название', max_length=250)

    def __str__(self):
        return self.name


class Student(models.Model):
    GRADE_CHOICES = (
        ('bachelor', 'Бакалавр'),
        ('master', 'Магистр')
    )

    full_name = models.CharField('Имя', max_length=200)
    birthday = models.DateField('Дата рождения')
    sex = models.CharField('Пол', max_length=20, choices=SEX_CHOICES, default='male')
    end_date = models.DateField('Дата окончания', blank=True, null=True)
    structural_unit = models.ForeignKey(Structural, verbose_name='Подразделение', on_delete=models.CASCADE)
    grade = models.CharField('Образовательный степень', max_length=50, choices=GRADE_CHOICES, default='bachelor')
    speciality = models.CharField('Специальность', max_length=250, blank=True, null=True)
    specialization = models.CharField('Специализация', max_length=250, blank=True, null=True)
    photo = ProcessedImageField(upload_to='photos',
                                processors=[ResizeToFill(200, 200)],
                                format='JPEG',
                                options={'quality': 60},
                                blank=True,
                                null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Employee(models.Model):
    full_name = models.CharField('Имя', max_length=200)
    birthday = models.DateField('Дата рождения')
    position = models.CharField('Должность', max_length=100, blank=True, null=True)
    department = models.CharField('Отдел', max_length=100, blank=True, null=True)
    photo = ProcessedImageField(upload_to='photos',
                                processors=[ResizeToFill(200, 200)],
                                format='JPEG',
                                options={'quality': 60},
                                blank=True,
                                null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Administration(models.Model):
    TYPE_CHOICES = (
        ('dean', 'Декан'),
        ('director', 'Керівник'),
        ('rector', 'Ректор')
    )

    full_name = models.CharField('Имя', max_length=200)
    birthday = models.DateField('Дата рождения')
    type = models.CharField('Тип', max_length=50, choices=TYPE_CHOICES)
    photo = ProcessedImageField(upload_to='photos',
                                processors=[ResizeToFill(200, 200)],
                                format='JPEG',
                                options={'quality': 60},
                                blank=True,
                                null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

templates/admin_notification.html
{% extends 'base.html' %}
{% block meta %}
        <meta property="og:image" content="{{ og_image }}">
{% endblock %}


{% block body %}

    <div class="container">
        <h2 class="">Сьгодні святкують день народження</h2>
        {% if structurals %}
            <div class="card mt-2">
                <div class="card-body">
                    <h5 class="card-title">Студенти</h5>
                    {% for structural in structurals %}
                        <div class="mt-2">
                            <div class="card-subtitle text-muted">{{ structural.name }}</div>
                            {% for student in structural.students %}
                                <li class="list-group-item">
                                <div class="row mt-2">
                                    <div class="col-2">
                                        {% if student.photo %}
                                            <img class="photo" src="{{ student.photo.url }}" alt="">
                                        {% else %}
                                            <img class="photo" src="{{ no_student_photo }}" alt="">
                                        {% endif %}
                                    </div>
                                    <div class="col-10">
                                        <div>{{ student.full_name }}</div>
                                        <div>{{ student.speciality }}</div>
                                    </div>
                                </div>
                                </li>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if employees %}
            <div class="card mt-2">
                <div class="card-body">
                    <h5 class="card-title">Співробітники</h5>
                    <ul class="list-group">
                        {% for employee in employees %}
                            <li class="list-group-item">
                                <div class="row  mt-2">
                                    <div class="col-2">
                                        {% if employee.photo %}
                                            <img class="photo" src="{{ employee.photo.url }}" alt="">
                                        {% else %}
                                            <img class="photo" src="{{ no_employee_photo }}" alt="">
                                        {% endif %}
                                    </div>
                                    <div class="col-10">
                                        <div>{{ employee.full_name }}</div>
                                        <div>{{ employee.department }}</div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}

        {% if administrations %}
            <div class="card mt-2">
                <div class="card-body">
                    <h5 class="card-title">Адміністрація</h5>
                    {% for admin in administrations %}
                        <li class="list-group-item">
                        <div class="row  mt-2">
                            <div class="col-2">
                                {% if admin.photo %}
                                    <img class="photo" src="{{ admin.photo.url }}" alt="">
                                {% else %}
                                    <img class="photo" src="{{ no_administration_photo }}" alt="">
                                {% endif %}
                            </div>
                            <div class="col-10">
                                <div>{{ admin.full_name }}</div>
                                <div>{{ admin.get_type_display }}</div>
                            </div>
                        </div>
                        </li>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>День народження</title>
    <meta property="og:title" content="Сьогодні день народження святкують">
    {% block meta %}
    {% endblock %}

    <style type="text/css">
        .photo {
            width: 100px;
            height: 100px;
        }
    </style>
</head>
<body>

{% block body %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>